baseurl = "https://l1990790120.github.io/"
languageCode = "en-us"
title = "LC"
theme = "custom-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "l1990790120"
# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-71133003-1"
# Posts per page
paginate = 10
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."

[[menu.main]]
    name = "About"
    url = "/about/"

[[menu.main]]
    name = "Generative Art"
    url = "/generative-art/"

[[menu.main]]
    name = "Blog"
    url = "/"

[params]
	author = "Lulu Cheng"
	description = "LC"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = "Machine Learning, Economics, Politics, Social Science, Software Engineering"
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "profile.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	# gravatar = "l1990790120@gmail.com"

	headerText = ""
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = "profile_pic.jpg"
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = false
		homepage = false
		email = "l1990790120@gmail.com"
		behance = ""
		bitbucket =""
		dribbble = ""
		facebook = "l1990790120"
		flickr = ""
		github = "l1990790120"
		instagram = "l1990790120"
		linkedin = "luluchengengineeratheart"
		pinterest = "l1990790120"
		reddit = "l1990790120"
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = "l1990790120"
		wordpress = ""
		youtube = "l1990790120"
		gitlab = ""
		trello = ""
		medium = "l1990790120"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true